name: Sync docs on push & PR merge

on:
  push:
    branches:
      - main
    paths:
      - 'docs/prds/**'
  pull_request:
    types: [closed]
    paths:
      - 'docs/prds/**'

jobs:
  sync_docs:
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to Google Docs
        uses: vtex/tooling-sync-gh-docs@v1.0.0
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        with:
          google_doc_id: ${{ secrets.GOOGLE_DOC_ID }}
          target_folder: docs/prds
